# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='running', max_length=10)),
                ('hash', models.CharField(max_length=32)),
                ('dictionary', models.PositiveSmallIntegerField(choices=[(1, 'Wszystkie'), (2, 'Cyfry'), (3, 'Male_litery'), (4, 'Duze_litery'), (5, 'Wszystkie_litery'), (6, 'Male_litery_Cyfry'), (7, 'Duze_litery_Cyfry')], default=2)),
                ('max_password_len', models.IntegerField(default=8)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='Brutfoce.User'),
        ),
    ]
