# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brutfoce', '0006_auto_20170615_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='input_password',
            field=models.CharField(default=b'haslo', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='output_password',
            field=models.CharField(default=b'haslo', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'submitted', b'Submitted'), (b'running', b'Running'), (b'paused', b'Paused'), (b'ended', b'Ended'), (b'canceled', b'Canceled')], default=b'submitted', max_length=10),
        ),
    ]
