# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brutfoce', '0007_auto_20170615_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcu',
        ),
        migrations.AlterField(
            model_name='task',
            name='output_password',
            field=models.CharField(default=b'', max_length=32),
        ),
    ]
